name: Build and Push Docker image

on:
  push:
    branches: [ osg-alma8-testing ]
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      harbor_username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
      harbor_password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    strategy:
      fail-fast: False
      matrix:
        dver: ['el7', 'el8', 'al8']
        repo: ['devel', 'testing', 'release']
        series: ['3.6']
        include:
            - harbor_url: hub.opensciencegrid.org
            - harbor_username: echo $harbor_username
            - harbor_password: echo $harbor_password
            - docker_url: docker.io
            - docker_username: echo $docker_username
            - docker_password: echo $docker_password

    steps:
      - id: custom-image-name
        env:
          SERIES: ${{ matrix.series }}
          REPO: ${{ matrix.repo }}
          OS: ${{ matrix.dver }}
        run: |
          PREFIX="output_image=${GITHUB_REPOSITORY}:${SERIES}"
          if [[ $OS == 'el8' ]]; then
            echo "${PREFIX}-${REPO}" >> ${GITHUB_OUTPUT}
          else
            echo "${PREFIX}-${OS}-${REPO}" >> ${GITHUB_OUTPUT}
          fi
      - id: build-image
        uses: opensciencegrid/build-container-action@v0.5.0
        with: 
          osg_series: ${{ matrix.series }}
          osg_repo: ${{ matrix.repo }}
          base_os: ${{ matrix.dver }}
          output_image: ${{ steps.custom-image-name.outputs.output_image }}
          registry_url: ${{matrix.registry}}
          registry_user: ${{matrix.registry}}
          registry_pass: ${{matrix.registry}}

      - name: Push to OSG Harbor
        if: >-
          github.ref == 'refs/heads/master' &&
          github.event_name != 'pull_request' &&
          github.repository_owner == 'opensciencegrid'
        env:
          IMAGE_LIST: ${{ steps.build-image.outputs.image-list}}
        run: |
          for registry in hub.opensciencegrid.org docker.io; do
            IFS=,
            for image in ${IMAGE_LIST}; do
              fqin=hub.opensciencegrid.org/${image}
              docker tag ${image} ${fqin}
              docker push ${fqin}
            done
          done
