name: Build and Push Docker image

on:
  push:
    branches: [ osg-alma8-testing ]
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        dver: ['el7', 'el8', 'al8']
        repo: ['devel', 'testing', 'release']
        series: ['3.6']

    steps:
      - id: custom-image-name
        env:
          SERIES: ${{ matrix.series }}
          REPO: ${{ matrix.repo }}
          OS: ${{ matrix.dver }}
        run: |
          PREFIX="output_image=${GITHUB_REPOSITORY}:${SERIES}"
          if [[ $OS == 'el8' ]]; then
            echo "${PREFIX}-${REPO}" >> ${GITHUB_OUTPUT}
          else
            echo "${PREFIX}-${OS}-${REPO}" >> ${GITHUB_OUTPUT}
          fi
      - id: build-image
        uses: opensciencegrid/build-container-action@v0.5.0
        with: 
          osg_series: ${{ matrix.series }}
          osg_repo: ${{ matrix.repo }}
          base_os: ${{ matrix.dver }}
          output_image: ${{ steps.custom-image-name.outputs.output_image }}
  push:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/master' &&
      github.event_name != 'pull_request' &&
      github.repository_owner == 'opensciencegrid'
    needs: [build]
    strategy:
      fail-fast: False
      matrix:
        dver: ['el7', 'el8', 'al8']
        repo: ['devel', 'testing', 'release']
        series: ['3.6']
        registry:
          - url: hub.opensciencegrid.org
            username: OSG_HARBOR_ROBOT_USER
            password: OSG_HARBOR_ROBOT_PASSWORD
          - url: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD
    steps:
      - uses: opensciencegrid/push-container-action@v0.8.0
        with:
          repo: ${{ matrix.repo }}
          osg_series: ${{ matrix.osg_series }}
          registry_url: ${{ matrix.registry.url }}
          registry_user: ${{ secrets[matrix.registry.username] }}
          registry_pass: ${{ secrets[matrix.registry.password] }}